// <auto-generated />
namespace LibManagementSystem_Updated.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixIssuedBookTable_new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixIssuedBookTable_new));
        
        string IMigrationMetadata.Id
        {
            get { return "202502130931007_FixIssuedBookTable_new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
